name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Enable Corepack
      run: corepack enable
    - name: Install modules
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Run tests
      uses: borales/actions-yarn@v4
      with:
        cmd: test # will run `yarn test` command